"""DataBase creation

Revision ID: 3ee67814e628
Revises: 
Create Date: 2024-07-05 19:07:46.529671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee67814e628'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bouquet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bouquet_name', sa.String(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('type_flowers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('add_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('add_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bouquet.photo_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('bouquet')
    # ### end Alembic commands ###
