"""delete table photo (include in bouquet)

Revision ID: ea8d953eb56b
Revises: 3ee67814e628
Create Date: 2024-07-07 15:23:35.865658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8d953eb56b'
down_revision: Union[str, None] = '3ee67814e628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.add_column('bouquet', sa.Column('photo_address', sa.String(), nullable=False))
    op.drop_constraint('bouquet_photo_id_key', 'bouquet', type_='unique')
    op.drop_column('bouquet', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bouquet', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('bouquet_photo_id_key', 'bouquet', ['photo_id'])
    op.drop_column('bouquet', 'photo_address')
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('add_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bouquet.photo_id'], name='photo_id_fkey')
    )
    # ### end Alembic commands ###
